// <auto-generated />
using System;
using MiUni.Api.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NetTopologySuite.Geometries;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace MiUni.Api.Migrations
{
    [DbContext(typeof(MiUniDbContext))]
    partial class MiUniDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "estado_reporte", new[] { "Pendiente", "Revisado", "Descartado" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "rol_usuario", new[] { "Estudiante", "Administrador" });
            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "pgcrypto");
            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "pgrouting");
            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "postgis");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Lugartag", b =>
                {
                    b.Property<Guid>("LugarId")
                        .HasColumnType("uuid")
                        .HasColumnName("lugar_id");

                    b.Property<Guid>("TagId")
                        .HasColumnType("uuid")
                        .HasColumnName("tag_id");

                    b.HasKey("LugarId", "TagId")
                        .HasName("lugartag_pkey");

                    b.HasIndex("TagId");

                    b.ToTable("lugartag", (string)null);
                });

            modelBuilder.Entity("MiUni.Api.Models.Camino", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<LineString>("Geometria")
                        .IsRequired()
                        .HasColumnType("geography(LineString,4326)")
                        .HasColumnName("geometria");

                    b.Property<string>("TipoSuperficie")
                        .HasColumnType("character varying")
                        .HasColumnName("tipo_superficie");

                    b.Property<bool>("Transitable")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("transitable");

                    b.HasKey("Id")
                        .HasName("camino_pkey");

                    b.HasIndex(new[] { "Geometria" }, "idx_camino_geometria");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex(new[] { "Geometria" }, "idx_camino_geometria"), "gist");

                    b.ToTable("camino", (string)null);
                });

            modelBuilder.Entity("MiUni.Api.Models.Carrera", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("Facultad")
                        .HasColumnType("character varying")
                        .HasColumnName("facultad");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("character varying")
                        .HasColumnName("nombre");

                    b.HasKey("Id")
                        .HasName("carrera_pkey");

                    b.ToTable("carrera", (string)null);
                });

            modelBuilder.Entity("MiUni.Api.Models.Categorium", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("Icono")
                        .HasColumnType("character varying")
                        .HasColumnName("icono");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("character varying")
                        .HasColumnName("nombre");

                    b.HasKey("Id")
                        .HasName("categoria_pkey");

                    b.ToTable("categoria", (string)null);
                });

            modelBuilder.Entity("MiUni.Api.Models.Documentofuente", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("Referencia")
                        .IsRequired()
                        .HasColumnType("character varying")
                        .HasColumnName("referencia");

                    b.Property<string>("TipoOrigen")
                        .IsRequired()
                        .HasColumnType("character varying")
                        .HasColumnName("tipo_origen");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasColumnType("character varying")
                        .HasColumnName("titulo");

                    b.Property<DateTime>("UltimaActualizacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ultima_actualizacion")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id")
                        .HasName("documentofuente_pkey");

                    b.ToTable("documentofuente", (string)null);
                });

            modelBuilder.Entity("MiUni.Api.Models.Etiquetum", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("character varying")
                        .HasColumnName("nombre");

                    b.HasKey("Id")
                        .HasName("etiqueta_pkey");

                    b.HasIndex(new[] { "Nombre" }, "etiqueta_nombre_key")
                        .IsUnique();

                    b.ToTable("etiqueta", (string)null);
                });

            modelBuilder.Entity("MiUni.Api.Models.Eventotemporal", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("Descripcion")
                        .HasColumnType("text")
                        .HasColumnName("descripcion");

                    b.Property<DateTime>("FechaFin")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_fin");

                    b.Property<DateTime>("FechaInicio")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_inicio");

                    b.Property<Guid?>("LugarId")
                        .HasColumnType("uuid")
                        .HasColumnName("lugar_id");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasColumnType("character varying")
                        .HasColumnName("titulo");

                    b.HasKey("Id")
                        .HasName("eventotemporal_pkey");

                    b.HasIndex(new[] { "LugarId" }, "idx_evento_lugar");

                    b.ToTable("eventotemporal", (string)null);
                });

            modelBuilder.Entity("MiUni.Api.Models.Favorito", b =>
                {
                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uuid")
                        .HasColumnName("usuario_id");

                    b.Property<Guid>("LugarId")
                        .HasColumnType("uuid")
                        .HasColumnName("lugar_id");

                    b.Property<DateTime>("FechaAgregado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_agregado")
                        .HasDefaultValueSql("now()");

                    b.HasKey("UsuarioId", "LugarId")
                        .HasName("favorito_pkey");

                    b.HasIndex("LugarId");

                    b.ToTable("favorito", (string)null);
                });

            modelBuilder.Entity("MiUni.Api.Models.Foto", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<bool>("EsPrincipal")
                        .HasColumnType("boolean")
                        .HasColumnName("es_principal");

                    b.Property<DateTime>("FechaSubida")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_subida")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid>("LugarId")
                        .HasColumnType("uuid")
                        .HasColumnName("lugar_id");

                    b.Property<string>("StorageKey")
                        .IsRequired()
                        .HasColumnType("character varying")
                        .HasColumnName("storage_key");

                    b.HasKey("Id")
                        .HasName("foto_pkey");

                    b.HasIndex(new[] { "LugarId" }, "idx_foto_lugar");

                    b.HasIndex(new[] { "LugarId" }, "idx_foto_unica_principal")
                        .IsUnique()
                        .HasFilter("(es_principal = true)");

                    b.ToTable("foto", (string)null);
                });

            modelBuilder.Entity("MiUni.Api.Models.Historialchat", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("Contenido")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("contenido");

                    b.Property<string>("ContextoUtilizado")
                        .HasColumnType("jsonb")
                        .HasColumnName("contexto_utilizado");

                    b.Property<DateTime>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_creacion")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Rol")
                        .IsRequired()
                        .HasColumnType("character varying")
                        .HasColumnName("rol");

                    b.Property<Guid>("SesionId")
                        .HasColumnType("uuid")
                        .HasColumnName("sesion_id");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uuid")
                        .HasColumnName("usuario_id");

                    b.HasKey("Id")
                        .HasName("historialchat_pkey");

                    b.HasIndex(new[] { "SesionId" }, "idx_historial_sesion");

                    b.HasIndex(new[] { "UsuarioId" }, "idx_historial_usuario");

                    b.ToTable("historialchat", (string)null);
                });

            modelBuilder.Entity("MiUni.Api.Models.Horariooperacion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<short>("DiaSemana")
                        .HasColumnType("smallint")
                        .HasColumnName("dia_semana");

                    b.Property<TimeOnly>("HoraApertura")
                        .HasColumnType("time without time zone")
                        .HasColumnName("hora_apertura");

                    b.Property<TimeOnly>("HoraCierre")
                        .HasColumnType("time without time zone")
                        .HasColumnName("hora_cierre");

                    b.Property<Guid>("LugarId")
                        .HasColumnType("uuid")
                        .HasColumnName("lugar_id");

                    b.HasKey("Id")
                        .HasName("horariooperacion_pkey");

                    b.HasIndex(new[] { "LugarId" }, "idx_horario_lugar");

                    b.ToTable("horariooperacion", (string)null);
                });

            modelBuilder.Entity("MiUni.Api.Models.Lugar", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("activo");

                    b.Property<Guid>("CategoriaId")
                        .HasColumnType("uuid")
                        .HasColumnName("categoria_id");

                    b.Property<string>("Descripcion")
                        .HasColumnType("text")
                        .HasColumnName("descripcion");

                    b.Property<DateTime>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_creacion")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("character varying")
                        .HasColumnName("nombre");

                    b.Property<short?>("Piso")
                        .HasColumnType("smallint")
                        .HasColumnName("piso");

                    b.Property<Point>("Ubicacion")
                        .IsRequired()
                        .HasColumnType("geography(Point,4326)")
                        .HasColumnName("ubicacion");

                    b.HasKey("Id")
                        .HasName("lugar_pkey");

                    b.HasIndex(new[] { "CategoriaId" }, "idx_lugar_categoria");

                    b.HasIndex(new[] { "Ubicacion" }, "idx_lugar_ubicacion");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex(new[] { "Ubicacion" }, "idx_lugar_ubicacion"), "gist");

                    b.ToTable("lugar", (string)null);
                });

            modelBuilder.Entity("MiUni.Api.Models.Productomenu", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("Descripcion")
                        .HasColumnType("character varying")
                        .HasColumnName("descripcion");

                    b.Property<bool>("EstaDisponible")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("esta_disponible");

                    b.Property<Guid>("LugarId")
                        .HasColumnType("uuid")
                        .HasColumnName("lugar_id");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("character varying")
                        .HasColumnName("nombre");

                    b.Property<decimal>("Precio")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("precio");

                    b.HasKey("Id")
                        .HasName("productomenu_pkey");

                    b.HasIndex(new[] { "LugarId" }, "idx_producto_lugar");

                    b.ToTable("productomenu", (string)null);
                });

            modelBuilder.Entity("MiUni.Api.Models.Puntointeresinterno", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("Descripcion")
                        .HasColumnType("character varying")
                        .HasColumnName("descripcion");

                    b.Property<Guid>("LugarId")
                        .HasColumnType("uuid")
                        .HasColumnName("lugar_id");

                    b.Property<short?>("Piso")
                        .HasColumnType("smallint")
                        .HasColumnName("piso");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("character varying")
                        .HasColumnName("tipo");

                    b.HasKey("Id")
                        .HasName("puntointeresinterno_pkey");

                    b.HasIndex(new[] { "LugarId" }, "idx_poi_lugar");

                    b.ToTable("puntointeresinterno", (string)null);
                });

            modelBuilder.Entity("MiUni.Api.Models.Reporteusuario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<int>("Estado")
                        .HasColumnType("integer");

                    b.Property<Guid?>("LugarId")
                        .HasColumnType("uuid")
                        .HasColumnName("lugar_id");

                    b.Property<string>("Motivo")
                        .IsRequired()
                        .HasColumnType("character varying")
                        .HasColumnName("motivo");

                    b.Property<Guid?>("ResenaId")
                        .HasColumnType("uuid")
                        .HasColumnName("resena_id");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uuid")
                        .HasColumnName("usuario_id");

                    b.HasKey("Id")
                        .HasName("reporteusuario_pkey");

                    b.HasIndex(new[] { "LugarId" }, "idx_reporte_lugar");

                    b.HasIndex(new[] { "ResenaId" }, "idx_reporte_resena");

                    b.HasIndex(new[] { "UsuarioId" }, "idx_reporte_usuario");

                    b.ToTable("reporteusuario", (string)null);
                });

            modelBuilder.Entity("MiUni.Api.Models.Resena", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<short>("Calificacion")
                        .HasColumnType("smallint")
                        .HasColumnName("calificacion");

                    b.Property<string>("Comentario")
                        .HasColumnType("text")
                        .HasColumnName("comentario");

                    b.Property<DateTime>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_creacion")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid>("LugarId")
                        .HasColumnType("uuid")
                        .HasColumnName("lugar_id");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uuid")
                        .HasColumnName("usuario_id");

                    b.HasKey("Id")
                        .HasName("resena_pkey");

                    b.HasIndex(new[] { "LugarId" }, "idx_resena_lugar");

                    b.HasIndex(new[] { "UsuarioId" }, "idx_resena_usuario");

                    b.ToTable("resena", (string)null);
                });

            modelBuilder.Entity("MiUni.Api.Models.Usuario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<Guid?>("CarreraId")
                        .HasColumnType("uuid")
                        .HasColumnName("carrera_id");

                    b.Property<string>("CorreoInstitucional")
                        .IsRequired()
                        .HasColumnType("character varying")
                        .HasColumnName("correo_institucional");

                    b.Property<DateTime>("FechaRegistro")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_registro")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("character varying")
                        .HasColumnName("nombre");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("character varying")
                        .HasColumnName("password_hash");

                    b.Property<int>("Rol")
                        .HasColumnType("integer");

                    b.Property<short?>("Semestre")
                        .HasColumnType("smallint")
                        .HasColumnName("semestre");

                    b.HasKey("Id")
                        .HasName("usuario_pkey");

                    b.HasIndex(new[] { "CarreraId" }, "idx_usuario_carrera");

                    b.HasIndex(new[] { "CorreoInstitucional" }, "usuario_correo_institucional_key")
                        .IsUnique();

                    b.ToTable("usuario", (string)null);
                });

            modelBuilder.Entity("Lugartag", b =>
                {
                    b.HasOne("MiUni.Api.Models.Lugar", null)
                        .WithMany()
                        .HasForeignKey("LugarId")
                        .IsRequired()
                        .HasConstraintName("lugartag_lugar_id_fkey");

                    b.HasOne("MiUni.Api.Models.Etiquetum", null)
                        .WithMany()
                        .HasForeignKey("TagId")
                        .IsRequired()
                        .HasConstraintName("lugartag_tag_id_fkey");
                });

            modelBuilder.Entity("MiUni.Api.Models.Eventotemporal", b =>
                {
                    b.HasOne("MiUni.Api.Models.Lugar", "Lugar")
                        .WithMany("Eventotemporals")
                        .HasForeignKey("LugarId")
                        .HasConstraintName("eventotemporal_lugar_id_fkey");

                    b.Navigation("Lugar");
                });

            modelBuilder.Entity("MiUni.Api.Models.Favorito", b =>
                {
                    b.HasOne("MiUni.Api.Models.Lugar", "Lugar")
                        .WithMany("Favoritos")
                        .HasForeignKey("LugarId")
                        .IsRequired()
                        .HasConstraintName("favorito_lugar_id_fkey");

                    b.HasOne("MiUni.Api.Models.Usuario", "Usuario")
                        .WithMany("Favoritos")
                        .HasForeignKey("UsuarioId")
                        .IsRequired()
                        .HasConstraintName("favorito_usuario_id_fkey");

                    b.Navigation("Lugar");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("MiUni.Api.Models.Foto", b =>
                {
                    b.HasOne("MiUni.Api.Models.Lugar", "Lugar")
                        .WithOne("Foto")
                        .HasForeignKey("MiUni.Api.Models.Foto", "LugarId")
                        .IsRequired()
                        .HasConstraintName("foto_lugar_id_fkey");

                    b.Navigation("Lugar");
                });

            modelBuilder.Entity("MiUni.Api.Models.Historialchat", b =>
                {
                    b.HasOne("MiUni.Api.Models.Usuario", "Usuario")
                        .WithMany("Historialchats")
                        .HasForeignKey("UsuarioId")
                        .IsRequired()
                        .HasConstraintName("historialchat_usuario_id_fkey");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("MiUni.Api.Models.Horariooperacion", b =>
                {
                    b.HasOne("MiUni.Api.Models.Lugar", "Lugar")
                        .WithMany("Horariooperacions")
                        .HasForeignKey("LugarId")
                        .IsRequired()
                        .HasConstraintName("horariooperacion_lugar_id_fkey");

                    b.Navigation("Lugar");
                });

            modelBuilder.Entity("MiUni.Api.Models.Lugar", b =>
                {
                    b.HasOne("MiUni.Api.Models.Categorium", "Categoria")
                        .WithMany("Lugars")
                        .HasForeignKey("CategoriaId")
                        .IsRequired()
                        .HasConstraintName("lugar_categoria_id_fkey");

                    b.Navigation("Categoria");
                });

            modelBuilder.Entity("MiUni.Api.Models.Productomenu", b =>
                {
                    b.HasOne("MiUni.Api.Models.Lugar", "Lugar")
                        .WithMany("Productomenus")
                        .HasForeignKey("LugarId")
                        .IsRequired()
                        .HasConstraintName("productomenu_lugar_id_fkey");

                    b.Navigation("Lugar");
                });

            modelBuilder.Entity("MiUni.Api.Models.Puntointeresinterno", b =>
                {
                    b.HasOne("MiUni.Api.Models.Lugar", "Lugar")
                        .WithMany("Puntointeresinternos")
                        .HasForeignKey("LugarId")
                        .IsRequired()
                        .HasConstraintName("puntointeresinterno_lugar_id_fkey");

                    b.Navigation("Lugar");
                });

            modelBuilder.Entity("MiUni.Api.Models.Reporteusuario", b =>
                {
                    b.HasOne("MiUni.Api.Models.Lugar", "Lugar")
                        .WithMany("Reporteusuarios")
                        .HasForeignKey("LugarId")
                        .HasConstraintName("reporteusuario_lugar_id_fkey");

                    b.HasOne("MiUni.Api.Models.Resena", "Resena")
                        .WithMany("Reporteusuarios")
                        .HasForeignKey("ResenaId")
                        .HasConstraintName("reporteusuario_resena_id_fkey");

                    b.HasOne("MiUni.Api.Models.Usuario", "Usuario")
                        .WithMany("Reporteusuarios")
                        .HasForeignKey("UsuarioId")
                        .IsRequired()
                        .HasConstraintName("reporteusuario_usuario_id_fkey");

                    b.Navigation("Lugar");

                    b.Navigation("Resena");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("MiUni.Api.Models.Resena", b =>
                {
                    b.HasOne("MiUni.Api.Models.Lugar", "Lugar")
                        .WithMany("Resenas")
                        .HasForeignKey("LugarId")
                        .IsRequired()
                        .HasConstraintName("resena_lugar_id_fkey");

                    b.HasOne("MiUni.Api.Models.Usuario", "Usuario")
                        .WithMany("Resenas")
                        .HasForeignKey("UsuarioId")
                        .IsRequired()
                        .HasConstraintName("resena_usuario_id_fkey");

                    b.Navigation("Lugar");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("MiUni.Api.Models.Usuario", b =>
                {
                    b.HasOne("MiUni.Api.Models.Carrera", "Carrera")
                        .WithMany("Usuarios")
                        .HasForeignKey("CarreraId")
                        .HasConstraintName("usuario_carrera_id_fkey");

                    b.Navigation("Carrera");
                });

            modelBuilder.Entity("MiUni.Api.Models.Carrera", b =>
                {
                    b.Navigation("Usuarios");
                });

            modelBuilder.Entity("MiUni.Api.Models.Categorium", b =>
                {
                    b.Navigation("Lugars");
                });

            modelBuilder.Entity("MiUni.Api.Models.Lugar", b =>
                {
                    b.Navigation("Eventotemporals");

                    b.Navigation("Favoritos");

                    b.Navigation("Foto");

                    b.Navigation("Horariooperacions");

                    b.Navigation("Productomenus");

                    b.Navigation("Puntointeresinternos");

                    b.Navigation("Reporteusuarios");

                    b.Navigation("Resenas");
                });

            modelBuilder.Entity("MiUni.Api.Models.Resena", b =>
                {
                    b.Navigation("Reporteusuarios");
                });

            modelBuilder.Entity("MiUni.Api.Models.Usuario", b =>
                {
                    b.Navigation("Favoritos");

                    b.Navigation("Historialchats");

                    b.Navigation("Reporteusuarios");

                    b.Navigation("Resenas");
                });
#pragma warning restore 612, 618
        }
    }
}
